apiVersion: v1
kind: Secret
metadata:
  name: pdi-postgres-secret
  namespace: pdi
type: Opaque
stringData:
  POSTGRES_PASSWORD: pdi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres
  namespace: pdi
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
        - name: postgres
          image: postgres:16-alpine
          env:
            - name: POSTGRES_DB
              value: pdi
            - name: POSTGRES_USER
              value: pdi
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  key: POSTGRES_PASSWORD
                  name: pdi-postgres-secret
          ports:
            - containerPort: 5432
---
apiVersion: v1
kind: Service
metadata:
  name: postgres
  namespace: pdi
spec:
  ports:
    - port: 5432
      targetPort: 5432
  selector:
    app: postgres
