apiVersion: apps/v1
kind: Deployment
metadata:
  name: pdi-web
  namespace: pdi
spec:
  replicas: 2
  selector:
    matchLabels:
      app: pdi-web
  template:
    metadata:
      labels:
        app: pdi-web
    spec:
      containers:
        - name: web
          image: ghcr.io/andersonflima/pdi-portal-web:latest
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: /
              port: 8080
          livenessProbe:
            httpGet:
              path: /
              port: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: pdi-web
  namespace: pdi
spec:
  ports:
    - port: 8080
      targetPort: 8080
  selector:
    app: pdi-web
